### ISSUE TITLE
Driver path not coming through

### ISSUE THREAD

**Issue by RichTeaMan** [erdi/webdriver-binaries-gradle-plugin#12]
Hi there,

I'm having a problem getting the driver path in my code. I gather it's supposed to appear as a system variable, but I've printed the variables in both Groovy and Java land but neither has the 'webdriver.gecko.driver' key.
 
My test task downloads the Firefox driver before executing so I know something is working.

```
task uiTest(type: Test) {
    dependsOn assemble, compileTestJava
    doLast {
        println System.properties
        javaexec {
            main = "cucumber.api.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = ['--plugin', 'pretty', '--glue', 'org.domco.connectfour.server.ui.stepdefs', 'src/test/resources']
        }
    }
}
```

Is there anything else you'd suggest?

**Comment by erdi** [comment]
The system property is set on the instance of `Test` tasks (via [Test#systemProperty(String, String)](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/Test.html#systemProperty-java.lang.String-java.lang.Object-)) and not in the JVM executing the build. If you would like to print system properties set on an instance of a `Test` task then this should do it:

```
task uiTest(type: Test) {
    doLast {
        println systemProperties
    }
}
```

**Comment by erdi** [comment]
If you want to get hold the binary path in your build the best way to do so is by [registering](https://github.com/erdi/webdriver-binaries-gradle-plugin/blob/ef1030853ba5c70ee2735a72e21529909e629fc7/src/main/groovy/com/energizedwork/gradle/webdriver/task/ConfigureBinary.groovy#L39) an instance of [`DriverBinaryAware`](https://github.com/erdi/webdriver-binaries-gradle-plugin/blob/ef1030853ba5c70ee2735a72e21529909e629fc7/src/main/groovy/com/energizedwork/gradle/webdriver/DriverBinaryAware.groovy) which receives the path of the binary upon its resolution:

```
configureGeckoDriverBinary {
    addBinaryAware { binaryPath ->
        //do something with binary path
    }
}
```

**Comment by RichTeaMan** [comment]
Thanks a lot. I ended up using the configureGeckoDriverBinary method to store and pass the path to a BDD Cucumber task.
