### ISSUE TITLE
Update the documentation considering "downloadRoot"

### ISSUE THREAD

**Issue by rfelgent** [erdi/webdriver-binaries-gradle-plugin#13]
Hello everybody,

first of all: you made a great tool!

I would like to suggest one small enhancement.

By giving an example of how to configure "downloadRoot" you would make clear that you do not accept a String but a File object as parameter.

This does not work:
`downloadRoot "/tmp/selenium_tests/bins"`

This works:
`downloadRoot new File("${project.buildDir}")`

Although it is a small issue, it might help other people anyway...

Regards

**Comment by erdi** [comment]
Thanks @rfelgent but I will not be updating the documentation with your suggestion. 

There are two reasons why:
1. Unless you are doing something advanced, `downloadRoot` property should not be modified - the default is good enough and will allow you to benefit from caching of binaries and reusing them between projects as already documented
2. The documentation already states that the type of that property is `File` and I believe that it's sufficient to know what value can and cannot be used to set it
