### ISSUE TITLE
No browser visible and no reports

### ISSUE THREAD

**Issue by rdmueller** [erdi/webdriver-binaries-gradle-plugin#15]
great plugin, but I still have to get it to work...

I had a small working test suite and replaced my driver download and setup mechanism with your plugin.
In addition to spock and geb, I use the spock-reports plugin and gep-spock-reports plugin:
 on a Win10 machine

    testCompile 'com.aoe:geb-spock-reports:0.1.5'
    testCompile ("com.athaydes:spock-reports:1.6.0") { transitive = false }

It seems that the chrome driver gets downloaded and tests run, but some tests fail because of a 

    org.openqa.selenium.ElementNotVisibleException: You may only interact with visible elements

exception. Thsi worked before - the invisible element is a drop down menu which gets activated right before.

But my main problem is that chrome runs completly headless (nothing to see) and all `report` statements seem to produce no screenshot. This makes it a blackbox.

Any idea what could be wrong?

**Comment by rdmueller** [comment]
btw: is there maybe an example project?

**Comment by erdi** [comment]
Ralf,

I am surprised that switching from your driver download mechanism to the plugin had any influence on your test behaviour. Assuming of course, that you are using the same version of the driver binary (including architecture, especially for the IE driver) when using both your custom implementation of downloading and the plugin I would not expect any difference in test behaviour.

I find it even more surprising that your chrome tests are out of the sudden running in headless mode. Again, this is something that I would not expect the plugin to have influence on.

There is no example project for the plugin but it comes with some [end to end tests](https://github.com/erdi/webdriver-binaries-gradle-plugin/blob/c616892a1cea5fc538fe58f695cd628ec552aa03/src/test/groovy/com/energizedwork/gradle/webdriver/WebDriverBinariesPluginSpec.groovy#L29) that can be used to prove that the setup works.

**Comment by rdmueller** [comment]
yes, I used the same version. I guess my problem have to do with the auto-config...

I will take a look at the tests and see if I can find the problem...

**Comment by erdi** [comment]
What do you mean by auto-config?

Do you possibly have a different version of the binary installed in your path which is being picked up? Can you confirm that the driver binary system property is set to the binary downloaded by the plugin from within your tests?

**Comment by rdmueller** [comment]
> auto-config

I was reffereing to

> When a configuration task is executed it modifies configuration of system properties for all  org.gradle.api.tasks.testing.Test tasks in the project so that the location of the WebDriver binary location is picked up when the driver is being initialized. That is, it adds a system property with a name specific to the given driver and a value being the path to the downloaded binary.

> Do you possibly have a different version of the binary installed in your path which is being picked up?

I will now see what I can get as debug info. I'll keep you updated :-)

>

**Comment by erdi** [comment]
Hey @rdmueller, what's the status of this? Can it be closed?

**Comment by rdmueller** [comment]
I still have to find a solution, but you are right, let's close it!
