### ISSUE TITLE
new json file?

### ISSUE THREAD

**Issue by trinidad8516** [erdi/webdriver-binaries-gradle-plugin#16]
Erdi, I know this project is using https://raw.githubusercontent.com/webdriverextensions/webdriverextensions-maven-plugin-repository/master/repository-3.0.json but this file and its usually out of date, I made [pull request](https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository/pull/45) to help maintain it but is not working do you think it would be a good idea to implement your own .json file I can help you maintain it. 

here is my raw file from that p.r. 

https://raw.githubusercontent.com/trinidad8516/webdriverextensions-maven-plugin-repository/master/repository-3.0.json

**Comment by erdi** [comment]
I have commented on the PR, let’s see what the maintainer comes back before me make a move on this

**Comment by trinidad8516** [comment]
yes I saw, thanks for getting back to me. let me know if I can help.

**Comment by andidev** [comment]
Yeah sorry about this. I'll try to be faster in the future. If anybody is intressted I can add them as a mainteiner to the project.

**Comment by trinidad8516** [comment]
yes, I would like to contribute as much as I can, at least to merge and keep things up to date.
