### ISSUE TITLE
Add fallback to 32bit if 64bit driver is not available

### ISSUE THREAD

**Issue by leonard84** [erdi/webdriver-binaries-gradle-plugin#17]
Some drivers are only available in 32bin (chromedriver for windows). Currently the plugin fails when it can't find a driver for the version. It would be better if it would try the 32bit as a fallback, since 32bit should always work on a 64bit machine.

Although it is possible to achieve this with 
```groovy
webdriverBinaries {
    chromedriver {
        if (OperatingSystem.current().isWindows()) {
            architecture = "X86"
        }
    }
}
```
an automatic handling would be better.

**Comment by jasin** [comment]
This should be fixed, but in the mean time the above does work.
