### ISSUE TITLE
Distribution Tasks 

### ISSUE THREAD

**Issue by visch** [erdi/webdriver-binaries-gradle-plugin#18]
I'll preface this with me saying I'm probably approaching this issue wrongly so if you guys have a better idea let me know!

Goal: Generate Runable jar using the webdriver plugin. Ultimately I want my distribution to run in a docker container. 

Currently: `gradle run`, works properly. When I run `gradle distZip `the bash file is missing the environment variables needed. 

Current gradle file:
```
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Groovy project to get you started.
 * For more details take a look at the Groovy Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/tutorial_groovy_projects.html
 */

plugins {
    // Apply the groovy plugin to add support for Groovy
    id 'groovy'

    // Apply the application plugin to add support for building an application
    id 'application'
    id "com.energizedwork.webdriver-binaries" version "1.4"
}

webdriverBinaries {
    chromedriver '77.0.3865.40'
}
repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the latest Groovy version for building this library
    implementation 'org.codehaus.groovy:groovy-all:2.5.6'
    implementation 'org.seleniumhq.selenium:selenium-chrome-driver:3.14.0'
    implementation 'org.gebish:geb-core:3.2'
     // Use the awesome Spock testing and specification framework
    testImplementation 'org.spockframework:spock-core:1.2-groovy-2.5'
}

run.dependsOn  {
    "configureChromeDriverBinary"
}

configureChromeDriverBinary.addBinaryAware(
    new com.energizedwork.gradle.webdriver.BinaryAwareProperties(
            run.systemProperties,'webdriver.chrome.driver'
    )
)

// Define the main class for the application
mainClassName = 'gebtest.App'


```

My two ways forward right now that I"m going to go for:
Plan A: My plan right now is to use `configureChromeDriverBinary` , and use that output to get the proper path.

Plan B: Put the entire source directory I have on a docker container I have, and run it with `gradle run`

Is there a better way? 

I of course (as a noob) want to just type
`gradle distZip` and have everything "auto magically" work.

**Comment by erdi** [comment]
I'm not sure if using this plugin to manage webdriver binaries inside of docker images is the right approach. This plugin has been designed to support automatic download of webdriver binaries onto developer machines and CI hosts as part of running tests. What you seem to be doing is trying to setup the binary inside of a docker image (as opposed to developer machine or CI host) and for an application (as opposed to some tests). Wouldn't an easier option be to use [one](https://hub.docker.com/r/selenium/standalone-chrome) of [the official docker images with the browser and webdriver binary preinstalled in them](https://hub.docker.com/u/selenium)?

**Comment by visch** [comment]
Yeah I'm using the wrong tool for the job. Thanks for the pointers, they were very helpful @erdi

**Comment by erdi** [comment]
You're welcome!
