### ISSUE TITLE
Gradle error looking for v2.1 .jar

### ISSUE THREAD

**Issue by treyturner** [erdi/webdriver-binaries-gradle-plugin#19]
I'm pretty sure this is a result of my own misunderstanding or confusion, but I'm having problems getting this plugin to resolve and am out of ideas so I thought to ask here. I have a multi-module Gradle project and have this plugin loaded into a few modules like so:

```
plugins {
    id "com.github.erdi.webdriver-binaries" version "2.1"
}
```

When Gradle tries to resolve this dependency, it looks for a .jar file that doesn't exist, as distribution seems to have moved to POM-only?

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':projectname'.
> Could not resolve all dependencies for configuration ':projectname:classpath'.
   > Could not determine artifacts for com.github.erdi.webdriver-binaries:com.github.erdi.webdriver-binaries.gradle.plugin:2.1
      > Could not get resource 'https://repo.foo.com/maven/com/github/erdi/webdriver-binaries/com.github.erdi.webdriver-binaries.gradle.plugin/2.1/com.github.erdi.webdriver-binaries.gradle.plugin-2.1.jar'.
         > Could not HEAD 'https://repo.foo.com/maven/com/github/erdi/webdriver-binaries/com.github.erdi.webdriver-binaries.gradle.plugin/2.1/com.github.erdi.webdriver-binaries.gradle.plugin-2.1.jar'. Received status code 403 from server: Forbidden
```

It's probably worth mentioning that I'm attempting to use a caching Artifactory repository hosted by my company, but I'm confident I have the repo (and authentication) properly setup as this is the only dependency giving me issues; that is to say that if I comment out this plugin and the webdriver blocks in my `build.gradle`, I can otherwise `clean` and `check` without issue.

The 403 response is really a 404 that is transformed to meet security policy; we don't want to expose which files exist so 404s are converted to 403s. If I navigate to `https://repo.foo.com/maven/com/github/erdi/webdriver-binaries/com.github.erdi.webdriver-binaries.gradle.plugin/2.1/` in a browser, I can see the .pom file there and download it without issue. What I can't figure out is how to make Gradle realize there is no .jar in the repo and to instead use the .pom. I understand when using the `dependencies` block you can tack `@pom` onto a version number to indicate this, but that doesn't seem to be supported in the `plugins` block.

Does anyone have advice for someone who's been away during these pom-only distribution developments? Is this a configuration issue on my part, or possibly with my repository? Thanks so much for your time.

**Comment by erdi** [comment]
My advice would be to configure credentials for the repo you are resolving plugins from so that it responds with a 404 and not a 403 for files that were not found. Basically 403 is treated as a resolution error and not as not found like 404 is. If you configure the credentials then your problem will go away. As far as I know it's not possible to tell Gradle to treat 403s as not found. Basically, Gradle has to understand that there is no jar file for that artifact.

**Comment by treyturner** [comment]
Thanks for the info; I wasn't aware Gradle might have issues with dependency resolution given a 403 response for a non-existant .jar. Seems like [this Artifactory feature](https://www.jfrog.com/jira/browse/RTFACT-8765) or [this bug](https://www.jfrog.com/jira/browse/RTFACT-13797), or maybe [this Gradle feature](https://github.com/gradle/gradle/issues/5606) could be related; unfortunately the first two are quite old and the latter was recently closed due to an apparent lack of interest.

I'm severely tied up on a number of fronts, but when possible I'll see if I can override the 403 response to a 404 with Fiddler and see if that has any impact.

Going to close this now though since the issue would appear to be with Artifactory and/or Gradle.

**Comment by erdi** [comment]
FWIW, I was affected by something similar lately and created this feature request: https://github.com/gradle/gradle/issues/11247. It stems from 401 statuses and not 403 like in your case and deals specifically with downloading source artifacts but it still feels somehow related.
