### ISSUE TITLE
Requesting support for Safari Driver

### ISSUE THREAD

**Issue by masterautomator** [erdi/webdriver-binaries-gradle-plugin#20]
Hello @erdi and team! We are very happy with Geb / Spock for all our automation needs This is an amazingly useful plug-in and so far we have been using it for Chrome, Firefox, IE. 

Now we need to also support Safari driver. Any chance Safari is supported as part of this plug-in? Thanks a lot!

**Comment by erdi** [comment]
According to [this article from 2016](https://webkit.org/blog/6900/webdriver-support-in-safari-10/) starting with Safari 10 there is no need to manually install a webdriver binary for Safari, therefore there is nothing for this plugin to support.

**Comment by masterautomator** [comment]
Thanks @erdi Happy New Year!
I have noticed that also after opening the issue. Thanks for closing the ticket.
