### ISSUE TITLE
Unable to download ChromeDriver in version 80.0.3987.106

### ISSUE THREAD

**Issue by askucins** [erdi/webdriver-binaries-gradle-plugin#22]
Right now there are two versions of Chromedriver for v80 on https://chromedriver.chromium.org/downloads
- 80.0.3987.106
- 80.0.3987.16

Yet when I'm trying to run chromeTest with the first one i'm getting this error:
````
Execution failed for task ':configureChromeDriverBinary'.
> com.github.erdi.gradle.webdriver.repository.DriverUrlNotFoundException: Driver url not found for name: "chromedriver", version: "80.0.3987.106", platform: "linux", bit: "64 or 32"
````
The second one works ok (driver is downloaded).

I'm using the geb-example-gradle project and run test via included gradle wrapper.

**Comment by askucins** [comment]
Ops. I'm sorry, I didn't checked that that version was indeed missing in the https://raw.githubusercontent.com/webdriverextensions/webdriverextensions-maven-plugin-repository/master/repository-3.0.json

**Comment by erdi** [comment]
No worries. It's great that you managed to get to the bottom of the issue without me having to point you at [the docs](https://github.com/erdi/webdriver-binaries-gradle-plugin#configuring-download-urls) which I was about to do anyway.
