### ISSUE TITLE
Execution failed for task ':configureChromeDriverBinary'.

### ISSUE THREAD

**Issue by panhaseav** [erdi/webdriver-binaries-gradle-plugin#23]
I really appreciate your work on this. For some reason, I  got an error after I tried to run the test files.I've been searching everywhere on the internet for a solution but not one that can fix the issues. My gradle version is v 5.6.4 and I am using grails framework version 4. Thank you so much.
[
![error](https://user-images.githubusercontent.com/57328179/90114808-757d0700-dd7d-11ea-9d46-44140d920eca.PNG)
](url)

**Comment by erdi** [comment]
There is no 64-bit version of chrome driver binary `2.45.0` for Windows, there's only a 32-bit version. You need to set [the `fallbackTo32Bit ` extension property to `true`](https://github.com/erdi/webdriver-binaries-gradle-plugin#extension-properties).

**Comment by panhaseav** [comment]
Hello, Thanks for the response. I set the fallbackTo32Bit to true and right now I got this error. Thank you.

![error1](https://user-images.githubusercontent.com/57328179/90201075-f0890080-de03-11ea-95b6-161e19b6dc5b.PNG)

**Comment by erdi** [comment]
I suspect you're not on the latest version of the plugin, are you?

**Comment by karthi4all** [comment]
Use the arthitecture attribute instead, it works fine, document mentioned in the first comment
```
chromedriver {
        version = '2.32'
        architecture = 'X86'
    }
```

**Comment by melchior-by** [comment]
Same error for me - nothing of listed solutions were helpful. 'geckodriver' works fine, but for 'chromedriver' - every time 'Execution failed for task ':configureChromeDriverBinary'.
> com.github.erdi.gradle.webdriver.repository.DriverUrlNotFoundException: Driver url not found for name: "chromedriver"'

**Comment by erdi** [comment]
What is the full error message, @melchior-by? It should also say which version, platform and architecture it was looking for. Attaching the full stacktrace would also be helpful.

**Comment by melchior-by** [comment]
![image](https://user-images.githubusercontent.com/1191632/111487119-2353f800-8749-11eb-92bb-b052fb49f725.png)

**Comment by erdi** [comment]
Yeah, this is because there is no version `2.32` for `chromedriver` at https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository/blob/master/repository-3.0.json. [There is `2.32.0`](https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository/blob/ee5ea9db98ba2e677aafae213ba701043adfd30b/repository-3.0.json#L1001), though, so if you change your config to that version then it should work.

**Comment by jose-83** [comment]
I get this error: 
`Execution failed for task ':configureChromeDriverBinary'.`
`'void org.gradle.wrapper.PathAssembler.<init>(java.io.File)'
`
using Gradle 7.4. 
Any idea what the problem is?

**Comment by erdi** [comment]
Your error in most likely unrelated to the one this ticket has been opened for, @jose-83. Please open a new ticket and provide information on what version you are using rather than hijack this issue.
