### ISSUE TITLE
Support for the 'new' Chrome-based Microsoft Edge

### ISSUE THREAD

**Issue by transentia** [erdi/webdriver-binaries-gradle-plugin#24]
I guess this is a request for enhancement, or for information about work-arounds?

Just like traditional Chrome, the (relatively) new Chrome-based Edge requires a webdriver to be downloaded, see:

https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp
(ignore the c-sharp bit in the url...)

Once one has the edgedriver, configuration (in Geb/Grails, for my situation) is familiar:

```
import org.openqa.selenium.Dimension
import org.openqa.selenium.edge.EdgeDriver
import org.openqa.selenium.edge.EdgeOptions

environments {

    edge {
        driver = {
            EdgeOptions options = new EdgeOptions()
            options.addArguments("headless")

            EdgeDriver driver = new EdgeDriver(options)

            //Resize current window to the set dimension
            driver.manage().window().setSize(new Dimension(1450,1024));

            println "EDGE driver created"
            driver
        }
    }
}
```

Can this be supported, please.

**Comment by erdi** [comment]
I've just published 2.3 which contains support for this. Thanks for submitting the request., @transentia.
