### ISSUE TITLE
Support aliases such as latest or latest_<majorversion>

### ISSUE THREAD

**Issue by demus-nine** [erdi/webdriver-binaries-gradle-plugin#25]
It would be nice to not have to keep modifying a hardcoded versionnumber to track the latest chrome release, which has had a tendency of breaking things every now and then.

**Comment by erdi** [comment]
This is already supported, at least from the point of view of this plugin - the version is just any string. All that is needed is to ensure that your [metadata source](https://github.com/erdi/webdriver-binaries-gradle-plugin#configuring-download-urls) has an entries for `latest` and `latest_<majorversion>`. 

I believe the [default metatada source](https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository/blob/master/repository-3.0.json) does not support it yet so you would need to either submit a PR to [WebDriver Extensions Maven Plugin Repository 3.0](https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository) with changes to the metadata source or switch to one that you maintain yourself (which you could store in a public github repo, for example) and configure the plugin as per [this section of the README](https://github.com/erdi/webdriver-binaries-gradle-plugin#configuring-download-urls).

**Comment by demus-nine** [comment]
But that still requires manual maintanance of which version is "latest".
The point of the change would be to have synthetic version number called "latest" or magic string, which is replaced by the highest versionnumber that is in the metadata source. This is mostly necessary because of chrome breaking things often but not always.

I haven't looked at the code, but I assume you load the metadata into an array of objects of some sort, that can be searched when looking for a matching version/architecture/os combination.

**Comment by erdi** [comment]
Oh, I see what you mean, thanks for the explanation.

I had a look and it seems fairly straightforward to implement. I'm planning to do some work on this project in the near future so I will consider your suggestion at the same time.

**Comment by erdi** [comment]
Note to self: looks like [ComparableVersion](https://maven.apache.org/ref/3.6.3/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ComparableVersion.html) from `maven-artifact` is a good candidate for comparing version strings.

**Comment by erdi** [comment]
Available in 2.4

**Comment by demus-nine** [comment]
Fantastic. Thanks. I'll fix up our builds immediately. :-)
