### ISSUE TITLE
AbstractMethodError in WebDriverBinaryMetadata 

### ISSUE THREAD

**Issue by musketyr** [erdi/webdriver-binaries-gradle-plugin#29]
When I want to run tests in the a Spring application (Java 11, Gradle 6.7.1) I get the following error:

```
java.lang.AbstractMethodError: Receiver class com.github.erdi.gradle.webdriver.WebDriverBinaryMetadata does not define or inherit an implementation of the resolved method abstract getProperty(Ljava/lang/String;)Ljava/lang/Object; of interface groovy.lang.GroovyObject.
```

(see [the build scan](https://scans.gradle.com/s/6tx3yiyxhsyi4/failure?expanded-stacktrace=WyIwIiwiMC0xLTIiXQ#1))

I've added you as a reader to the project. The particular commit you can use for reproduction is [here](https://github.com/manning-lp/musketyr-modifying-an-existing-feature-using-tdd-lp/commit/bb25a99db9e4467c41d2b14624d7469f59114a54).

**Comment by erdi** [comment]
Closing  due to no reply.
