### ISSUE TITLE
Plugin requests 32bit version of Chromedriver on M1 Mac

### ISSUE THREAD

**Issue by apiorecki** [erdi/webdriver-binaries-gradle-plugin#32]
Seems that the plugin always requests 32bit version of chromedriver on M1 Mac's:

Caused by: org.gradle.internal.UncheckedException: com.github.erdi.gradle.webdriver.repository.DriverUrlNotFoundException: Driver url not found for name: "chromedriver", version regexp: "\Q2.45.0\E", platform: "mac", bit: "32"

However chromedriver 32bit mac version has been dropped since version 2.23...

Unfortunately I'm unable to upgrade to newer than 2.4.1 of this plugin due to Gradle/Groovy version restrictions - so unable to test if this has been fixed in newer versions.

Any advice ? Don't want to rollback chromedriver version...

Update:

Managed to get around it by forcing 64bit:

```
webdriverBinaries {
        chromedriver {
            version = '2.45.0'
            architecture = 'X86_64'
        }
}
```

**Comment by erdi** [comment]
Closing as you seem to have fixed it.
