### ISSUE TITLE
Please publish 3.0 sources

### ISSUE THREAD

**Issue by jochenberger** [erdi/webdriver-binaries-gradle-plugin#37]
There seems to have been a 3.0 release last week, but the Github repo does not list the respective commit. Could you please push them?

**Comment by erdi** [comment]
It’s been pushed now. Apologies, the release was rejected by the plugin portal initially and when the issue was resolved by Gradle support I simply forgot to push the changes I had committed locally.

**Comment by jochenberger** [comment]
Thanks! :slightly_smiling_face:
