### ISSUE TITLE
Add Support for repository.json of webdriverextensions-maven-plugin

### ISSUE THREAD

**Issue by leonard84** [erdi/webdriver-binaries-gradle-plugin#9]
The current maven equivalent of this plugin is https://github.com/webdriverextensions/webdriverextensions-maven-plugin

It uses a json file https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository/blob/master/repository-3.0.json to be able to lookup the latest versions as well as the respective download url.

The plugin allows the user to change the url of the json, which in turn enables the use of a localized repository, by simply pointing to a local json which has local links.

Furthermore, it is already maintained by the webdriverextensions team so apart from the initial investment there shouldn't be much to do.

**Comment by erdi** [comment]
While I like the solution with a file to control where given versions can be downloaded from and which versions are available it will be some work task to change things to use a file like that. 

Can you please explain your use case for using a "localized repository" for the archives containing the binaries? Is it just to avoid downloading it from internet when the archive is available locally?

**Comment by leonard84** [comment]
@erdi The usecase is that some organizations want to limit access to the internet for the internal infrastructure, e.g. by using Artifactory to proxy public maven repositories. It is more a security and stability feature, than to save bandwidth, although this is also a factor as well as speed.

**Comment by irstevenson** [comment]
Oops, kind of missed this when I whipped up #10 . However, maybe what I describe in that ticket is a simple alternative to this.

But in the end, what @leonard84 is the same situation I/we have where I work.

**Comment by erdi** [comment]
Yeah, I now see the point in this feature. It's going to be a bit of work to implement it but I think it's totally worth it, especially now there are two people who'd find it useful. The plan is to implement this at some point in the near future.
